### PR TITLE
Rsync fixes

### PR DESCRIPTION
**Pull request by mikerenfro**
From README.md:

> * **`rsync_enabled`** (`Boolean`) *(defaults to: `true`)*
> 
> Whether to use rsync to efficiently pull initial boot files from a
> central location (i.e., the rsync server) and install them into
> `$tftpboot_root_dir/$linux_install_dir`.

It looks like the `rsync` in `config.pp` went to `$tftpboot_root_dir`, not to  `$tftpboot_root_dir/$linux_install_dir`.

There's also a consistent flipping of ownership and permissions on the `linux_install_dir` folder, due to the rsync:

> `Notice: /Stage[main]/Tftpboot::Config/File[/var/lib/tftpboot/linux-install]/owner: owner changed 448 to 'root' (corrective)`
> `Notice: /Stage[main]/Tftpboot::Config/File[/var/lib/tftpboot/linux-install]/group: group changed 1731 to 'nobody' (corrective)`
> `Notice: /Stage[main]/Tftpboot::Config/File[/var/lib/tftpboot/linux-install]/mode: mode changed '0755' to '0750' (corrective)`
> `Notice: Rsync[tftpboot](provider=rsync): .d...pog..x ./`
> `Notice: Applied catalog in 5.65 seconds`

Working on fixing that currently. Can squash these down to a single commit if needed.

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@mikerenfro Thanks for posting this! We're going to have to take a close look at the docs and tests prior to merging since they currently seem to work properly and we need to make sure that it wasn't actually a doc bug.

**Comment by mikerenfro** [comment]
Working on updating test specs, assuming the documentation is correct.

**Comment by mikerenfro** [comment]
Though I've gotten the owner and group settings to comply, there will need to be a corresponding `preserve_perms` flag available in the rsync module to allow local permissions to take . Making the necessary changes in my fork now.

Since I want to leave the permissions flag with the original behavior by default (`-p` for `preserve_perms => true`), I'll need to explicitly specify `preserve_perms => false` in the tftpboot module. That will mean my Travis tests will fail until the rsync module is updated or we go an entirely different route.

**Comment by trevor-vaughan** [comment]
Interesting. Thinking about the rsync update, adding support for `-p` certainly makes sense. Do you think that we should also provide a way to just pass arbitrary arguments into the rsync command line?

**Comment by mikerenfro** [comment]
I'm ok with arbitrary arguments to rsync, but I've got the necessary changes in to the rsync module that didn't require any additional parameters other than preserve_perms. Going to rebase/squash what I've got for both modules momentarily.

**Comment by mikerenfro** [comment]
Squashed and rebased. Looks like there are still Travis errors that might be irrelevant.

**Comment by trevor-vaughan** [comment]
@mikerenfro The actual rsync call was correct, so I reverted that and changed the documentation to be correct.

Took the opportunity to go ahead and update some of the tests and docs while poking around.

**Comment by op-ct** [comment]
@mikerenfro FYI, PR #49/[SIMP-8459] has been submitted to remove the `preserve_* => false` rsync attributes this patch introduced.  During 6.5.0 release testing, we noticed that (on default SIMP installations,) those attributes resulted in locked down, root-only file ownership/permissions, which prevent the tftpd service from reading the boot image files.  

We weren't able to reproduce the consistent flipping of ownership and permissions in your log snippet, but from the odd anonymous uid/gid they were changing from (448/1731), it seems likely that was the ownership of the files in the rsync source directory.   As those permissions didn't match the permissions tftpd expects (`root:nobody 0750`), the puppet file resource would have set them back each time.

**Pull request merged**
